name: explode JSON

on:
  workflow_dispatch:
  
jobs:
  read:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - name: list
      run: ls _data/
    - id: set-matrix
      run: |
        JSON=$(cat _data/recipes.json)
        echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  write:
    needs: read
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.read.outputs.matrix)}}
    steps:
    - run: echo ${{matrix}}
